export const quotes = [
    "Każdy krok przybliża Cię do celu!",
    "Twoja wytrwałość to Twoja siła!",
    "Małe kroki prowadzą do wielkich wyników!",
    "Nie poddawaj się, nawet jeśli jest ciężko.",
    "Twoje ciało może wszystko, to Twój umysł musi się przekonać.",
    "Każdy dzień to nowa szansa na sukces.",
    "Trening to inwestycja w siebie.",
    "Pokonuj swoje słabości, nie konkurentów.",
    "Zacznij tam, gdzie jesteś. Użyj tego, co masz.",
    "Małe kroki prowadzą do wielkich rezultatów.",
    "Codziennie bądź lepszą wersją siebie.",
    "\"Jedynym sposobem na wykonanie wielkiego dzieła jest pokochanie tego, co robisz.\" - Steve Jobs",
    "\"Jedyną przeszkodą między tobą a twoim celem jest historia, którą ciągle sobie powtarzasz i która opowiada o tym... dlaczego nie możesz go osiągnąć.\" - Jordan Belfort",
    "\"Nie bój się porażki. To nie koniec, to tylko początek.\" - Barack Obama",
    "\"Trudne drogi często prowadzą do pięknych destynacji.\" - Zig Ziglar",
    "\"Jeśli masz marzenie, musisz je doścignąć.\" - Will Smith",
    "\"Nigdy nie jest za późno, aby być tym, kim chcesz być.\" - George Eliot",
    "\"Wszystko, co możemy zrobić, to to, co jest przed nami.\" - J.R.R. Tolkien",
    "\"Nasze największe słabości leżą w rezygnacji.\" - Thomas Edison",
    "\"Nigdy nie bój się wyznaczyć sobie zbyt wysokich celów; nawet jeśli nie osiągniesz ich, będziesz miał coś wartościowego.\" - Michał Anioł",
    "\"Sukces to nie ostateczność, porażka to nie fatalność: to odwaga, by kontynuować, jest tym, co się liczy.\" - Winston Churchill",
    "\"Sukces to suma małych wysiłków, powtarzanych dzień po dniu.\" - Robert Collier"
    
];